# Generated by Django 4.0.4 on 2022-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avatar',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
