# Generated by Django 4.0.4 on 2022-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/'),
        ),
    ]
